# -*- coding: utf-8 -*-
"""Neural Prophet.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1dGbOzs0yjiccGSyQWLyooM6WK44KRNi3

# Neural Prophet

Here we will forecast the future of inflation using Neural Prophet.

### 1. Installing Neural Prophet
"""

!pip install neuralprophet

"""### 2. Preparing the datasets & Importing neccessary libraries"""

!git clone https://github.com/farelarden/Dicoding-Capstone-ML.git

import pandas as pd
from neuralprophet import NeuralProphet
from matplotlib import pyplot as plt
import pickle

df_Makanan = pd.read_csv('/content/Dicoding-Capstone-ML/Dataset/Fix Dataset/fix 02 - Makanan.csv')
df_Minuman = pd.read_csv('/content/Dicoding-Capstone-ML/Dataset/Fix Dataset/fix 02 - Minuman.csv')
df_Rumah = pd.read_csv('/content/Dicoding-Capstone-ML/Dataset/Fix Dataset/fix 03 - Rumah.csv')
df_Sandang = pd.read_csv('/content/Dicoding-Capstone-ML/Dataset/Fix Dataset/fix 04 - Sandang.csv')
df_Transportasi = pd.read_csv('/content/Dicoding-Capstone-ML/Dataset/Fix Dataset/fix 07 - Transportasi.csv')

"""### 3. Preparing the dataset"""

df_Makanan = df_Makanan[['KOTA MEULABOH','BULAN']]
df_Makanan.columns = ['y', 'ds']

df_Makanan.head()

"""### 4. Train the data"""

m = NeuralProphet()

model = m.fit(df_Makanan, freq='M', epochs=1000)

"""### 5. Forecasting"""

future = m.make_future_dataframe(df_Makanan, periods=900)
forecast = m.predict(future)
forecast.head()

plot1 = m.plot(forecast)

plt2 = m.plot_components(forecast)

forecast_value = forecast.loc[forecast.ds == '2021-10-31',['yhat1']].values[0]

forecast_value

